version: '3.4'
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.33.0.0/16
services:
  remoteconnect.avado.dnp.dappnode.eth:
    image: 'remoteconnect.avado.dnp.dappnode.eth:0.0.29'
    build: ./build
    volumes:
      - 'zt-data:/var/lib/zerotier-one'
      - 'data:/data'
    ports:
      - '22:22'
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    restart: always
    logging:
      options:
        max-size: 10m
        max-file: '3'
    dns: 172.33.0.2
    networks:
      network:
        ipv4_address: 172.33.1.20
volumes:
  data: {}
  zt-data: {}
